### ISSUE TITLE
광고 왜 없앰 ㅡㅡ

### ISSUE THREAD

**Issue by NazMc145** [blurfx/KakaoTalkAdBlock#1]
카톡도 사람이야 사람!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by blurfx** [comment]
따로 얘기하여 당사자와 잘 해결했습니다.

**Comment by ComputerPark** [comment]
ㅋㅋㅋ 이거뭐에요 ㅋㅋ
