### ISSUE TITLE
안녕하세요~ 좋은 프로그램 정말 감사합니다.

### ISSUE THREAD

**Issue by dldldlfma** [blurfx/KakaoTalkAdBlock#22]
안녕하세요 개발자님!

요즘에 개인적인 사정으로 카톡에 특정광고가 반복해서 뜨는게 
너무 힘들었는데 좋은 프로그램 올려주신 덕분에 마음이 한결 편안해 졌습니다.

정말 감사합니다~!

**Comment by blurfx** [comment]
감사합니다!
