### ISSUE TITLE
Pop-up ads are not blocked

### ISSUE THREAD

**Issue by blurfx** [blurfx/KakaoTalkAdBlock#23]

**Comment by Coding-Young** [comment]
관리자 권한으로 실행한 메모장을 이용하여 C:\Windows\System32\drives\etc\hosts 파일의 접속 차단 목록에 display.ad.daum.net을 추가하면 우하단의 광고 배너가 뜨지 않는 것으로 보이니 해당 현상으로 불편함을 겪고 계신 분들을 참고해보세요.
