### ISSUE TITLE
카카오톡 실행시 함께 켜지도록 하는 옵션이 있으면 좋을 것 같아요.

### ISSUE THREAD

**Issue by dmsalsgh97** [blurfx/KakaoTalkAdBlock#27]
카카오톡 실행시 함께 켜지고 꺼지도록 하는 옵션이 있으면 좋을 것 같아요.

**Comment by blurfx** [comment]
현재는 백그라운드로 광고 차단기가 실행된 상태에서 카카오톡의 실행 상태를 감지하여 처리하고 있습니다.

함께 꺼지거나 켜지는 것을 구현하려면 이를 위해 카카오톡의 실행 상태를 감지하는 프로세스가 추가적으로 하나 더 필요하며, 이 구현은 리소스 낭비라 생각되어 따로 작업하지 않겠습니다.
