### ISSUE TITLE
이거 삭제 어떻게 하나요?

### ISSUE THREAD

**Issue by lull941** [blurfx/KakaoTalkAdBlock#28]
깔고나서 노트북이 이상해져서 지울려는데
제어판에서 지워도 계속 남아있네요..ㅠㅠ 삭제 어떻게 하나요

**Comment by blurfx** [comment]
테스트해보니 켜져있는 상태에서 삭제를 시도하면 언인스톨러가 그대로 남겨두는 것 같습니다.

혹시 켜져있는 상태에서 삭제를 시도하셨다면, 트레이에서 종료 시킨 뒤 삭제를 시대해보세요.

그래도 문제가 해결되지 않으신다면 `%LocalAppData%\Apps\2.0`의 폴더 중 `kaka...`로 시작하는 폴더를 가지고 있는 폴더를 삭제해주세요.
