### ISSUE TITLE
시스템 종료 창 이슈

### ISSUE THREAD

**Issue by gpiece** [blurfx/KakaoTalkAdBlock#29]
해당 프로그램 이용 시 윈도우 부팅 후 로그온이 되면 갑자기 모든 프로그램이 종료되면서 시스템 종료 창이 뜹니다
이 프로그램이 깔려있는 PC에서 공통으로 일어나는 현상이니 확인해주시기 바랍니다
**처음엔 PC 부품이나 윈도우 설정 문제인줄 알고 식겁했는데 이 프로그램이 로그온 후 자동 실행되는 PC에서 나타나니 꼭 확인해주시기 바랍니다**

**Comment by incheon-kim** [comment]
저도 간헐적으로 발생했는데 이 프로그램이 발생시키는 문제였군요 ㅜ.ㅠ

**Comment by Saebyeol98** [comment]
0.12에서도 해당 증상이 간혈적으로 일어납니다 수정을 원합니다.

**Comment by blurfx** [comment]
1.0 이후로는 이 증상이 보이지 않는 것 같아 이슈 닫겠습니다.
같은 증상이 다시 발생한다면 이슈 다시 열어주세요.
