### ISSUE TITLE
Ads are not removed

### ISSUE THREAD

**Issue by luxroot** [blurfx/KakaoTalkAdBlock#32]
I think ads are not removed in 0.0.12 version
![image](https://user-images.githubusercontent.com/27440952/113118371-5d91bf00-924a-11eb-8c30-2b290260720f.png)
You can see that kakaotalkadblock is running but ads are still there.

KakaoTalk Ver. 3.2.4.2717
Adblock ver.0.0.12 

Should I offer more informations?

+ Update
This issue may be related to dotnet 5.0 not kakaotalkadblock v0.0.12 itself.

**Comment by blurfx** [comment]
I'm using the same Kakao Talk version and Adblock version, but I couldn't reproduce this problem.

Have you ever restart Adblock?

**Comment by luxroot** [comment]
When I updated program from v0.0.11, it was fine. But with clean installation, it doesn't work.
The result was same even after re-installing the windows.
I tried restarting, reinstalling AdBlock several times but it didn't work.

**Comment by blurfx** [comment]
Could you provide me the version and build number of Windows that you using?

You can check version and build number through run `winver`

**Comment by luxroot** [comment]
I'm using Microsoft Windows 20H2 [Version 10.0.19042.867]
I'll test one more time using windows VM

**Comment by luxroot** [comment]
I tested in VM and the result was the same... I don't know why it's happening :sob:

**Comment by blurfx** [comment]
Thank you for testing. I will try the test in the same environment on the weekend. If you have any other problems or information, please let me know.

**Comment by blurfx** [comment]
I'm sorry for late. I tried to reproduce the issue several times but failed. :(  Could you send me a snapshot of the virtual environment that having an issue?

**Comment by luxroot** [comment]
I think this issue is related to dotnet v5.0. After installing https://dotnet.microsoft.com/download/dotnet/5.0 , ads are not removed.
Sorry, I thought installing visual studio (or dotnet sdk 5.0 only) was irrelevant to this issue. If you can't reproduce this issue, please let me know.

**Comment by blurfx** [comment]
After a few tests, it doesn't seem like related to dotnet 5.x. I can't reproduce the issue again.

I think something else is the cause of this issue. Hmm. What is your system language?

**Comment by luxroot** [comment]
그러면 한국어 vm에서도 테스트해보겠습니다,,,,
맨처음 영어 윈도우에서 그냥 카톡설치시 광고가 숨겨졌다가 닷넷 sdk설치 후에 광고가 안 사라지긴 했습니다

**Comment by blurfx** [comment]
넵 알겠습니다. 영어 윈도우즈에서 말씀하신 조건으로 다시 테스트 해보겠습니다.

**Comment by luxroot** [comment]
네네 하겠습니다!! 원인을 몰라서 답답하네요 ㅜㅜㅜ

**Comment by blurfx** [comment]
[logger/issue-32](https://github.com/blurfx/KakaoTalkAdBlock/tree/logger/issue-32) 브랜치에 로거를 적용한 바이너리와 코드를 올려두었습니다.

해당 브랜치의 [/publish](https://github.com/blurfx/KakaoTalkAdBlock/tree/logger/issue-32/publish) 폴더에 있는 미리 빌드된 바이너를 사용해주시거나 혹은 직접 빌드하신 다음 실행시켜주시면 됩니다.

기존 배포된 바이너리와는 다르게 실행 후 바이너리가 위치된 폴더에 `kakaotalkadblock-logs.txt` 파일을 생성하고 해당 파일에 로그를 남기고 바로 종료됩니다. 
혹시 모르니 카카오톡을 종료하시고 다시 시작해주신 후 잠금모드까지 해제 후 해당 로깅용 바이너리를 실행시켜주세요.

저장된 로그는 iam [at] xo [dot] dev 로 보내주시면 감사하겠습니다.

**Comment by luxroot** [comment]
`FindWindowEx` 함수가 영문 윈도우즈에서 한글 `lpszWindow` 를 처리하지 못하는 문제입니다.
실 사용중인 영문 윈도우즈에서는 찾아지는 거로 보아 무언가 다른 문제와 결합되어 있을 수도 있습니다.

**Comment by blurfx** [comment]
가능하시다면 이슈를 해결하는 PR을 올려주시면 감사하겠습니다. 혹은 제가 오늘 저녁에 작업하여 새 버전을 배포하겠습니다.

**Comment by luxroot** [comment]
@baekilda 해결책 감사합니다. 프로그램단에서 해결할 수 있는 문제면 해결해 보겠습니다!
