### ISSUE TITLE
설치가 안됨

### ISSUE THREAD

**Issue by sleepylion99** [blurfx/KakaoTalkAdBlock#34]
![화면 캡처 2021-05-14 191855](https://user-images.githubusercontent.com/45265085/118257149-413f9e00-b4e9-11eb-90cd-1d3febfded56.png)

첨에는 위 상태 에서 넘아가고 파일 다운 까지 되었지만 실행 버튼 안떠서 강제 종료를 하였습니다

그랬더니 그뒤로 위 상태에서 오랫동안 있다가 아래 상태 처럼 나옵니다 ( 레지스트리 적용 해봐도 안되네요)
어떻게 해야할까요? (로그 첨부 해봅니다)
![2](https://user-images.githubusercontent.com/45265085/118257359-81068580-b4e9-11eb-961a-b1ba4467f316.png)
[FKTIQYPO.log](https://github.com/blurfx/KakaoTalkAdBlock/files/6478165/FKTIQYPO.log)

**Comment by sleepylion99** [comment]
다른 문구가 떠서 추가로 올려봅니다

[ASRJHO5L.log](https://github.com/blurfx/KakaoTalkAdBlock/files/6478235/ASRJHO5L.log)
![3](https://user-images.githubusercontent.com/45265085/118259125-bb712200-b4eb-11eb-83d0-80a2a9bd3326.png)

**Comment by kenramedik** [comment]
저도 레지스트리 적용해봐도 이렇게 뜨면서 안되네요;;

**Comment by blurfx** [comment]
원 이슈는 Windows 10 21376 인사이더 빌드의 문제로 보입니다.
