### ISSUE TITLE
카톡 창을 열게되면 카톡 광고가 뜨는데, 마우스를 올리거나 하면 사라집니다....근데 더러워요....

### ISSUE THREAD

**Issue by KRDevEgg** [blurfx/KakaoTalkAdBlock#38]
![123_censored](https://user-images.githubusercontent.com/43488826/123954810-c91f3000-d9e3-11eb-9aa1-bf9e92df30fd.jpg)
![제목 없음_censored](https://user-images.githubusercontent.com/43488826/123954819-ca505d00-d9e3-11eb-8991-fe6509406d1a.jpg)

처음에는 카톡 광고가 잘 사라지지만, 채팅창을 열 때 광고가 같이 나옵니다.
광고 위로 마우스를 올리면 그 부분만 사라집니다.
카카오톡 채팅창이 아닌 카카오톡 창을 클릭할 시 전부 사라집니다.
빠르게 수정 부탁드려요.

**Comment by blurfx** [comment]
Duplicated #37
