### ISSUE TITLE
v3.2.9.2808 버전 대응 업데이트 이후 UI 깨짐 문제

### ISSUE THREAD

**Issue by hw0603** [blurfx/KakaoTalkAdBlock#41]
![캡처](https://user-images.githubusercontent.com/31981462/124015604-d35f1f80-da1f-11eb-8b28-f9c66ef61b69.PNG)
![화면 캡처 2021-07-01 035417](https://user-images.githubusercontent.com/31981462/124015869-05708180-da20-11eb-8ec5-17370fde278b.png)

전체 창 높이 중에서 광고창 높이만큼 UI가 올라가고, 하단 광고부는 검은색으로 표시됩니다.

(시스템 배율 110%, 카카오톡 배율 125%입니다.)

**Comment by blurfx** [comment]
윈도우10 (19042.1052) 에서는 시스템 배율 110%가 없어 시스템 배율 125%, 카카오톡 배율 125%로 테스트를 해보았는데 정상 작동합니다.

문제가 생기시는 OS의 버전과 시스템 로케일 설정, 카카오톡 버전을 알려주세요.

**Comment by blurfx** [comment]
Windows 10 19043.1052 에서 시스템 배율 110%, 카카오톡 배율 125%로 테스트하였으나 역시 정상작동합니다.

**Comment by hw0603** [comment]
Windows 10 21H1(19043.1052), 카카오톡 버전 v3.2.9.2808 동일합니다. 시스템 로케일 ko-kr이고, 시스템 배율과 카카오톡 배율을 100%로 설정해도 동일 문제가 발생하네요..
#40 버전의 setup.exe가 없어서 clone한 다음에 원래 설치된 경로에 덮어씌웠는데, 혹 설치법이 잘못된 걸까요?

**Comment by blurfx** [comment]
버전별 인스톨러는 따로 제공되지 않고 `master` 브랜치의 `publish/setup.exe`나 kakao.xo.dev 에서 설치하시면 됩니다.

혹시 가능하시다면, 가상 머신에서 같은 문제를 재현하시고 해당 가상 머신의 이미지를 이메일로 전달해주실 수 있으실까요?

**Comment by hw0603** [comment]
원래 간헐적으로 나타나던 증상이였는데, 프로그램 재설치 후 아직까지는 증상이 발생하지 않네요. 혹시 다시 나타난다면 이 이슈에 다시 남겨놓겠습니다!

**Comment by hw0603** [comment]
오늘 동일 증상이 나타나서 테스트를 해 보니 카카오톡 메인 윈도우(채팅 윈도우 제외)의 크기가 조정되었을 때 하단부에 검은색 레터박스가 생기는 것 같습니다. 100%, 125% 모두 같은 증상입니다.

**Comment by blurfx** [comment]
Adblock이 실행중인 상태에서도 검은색 영역이 나타나나요?

**Comment by hw0603** [comment]
네 Adblock 버전 v1.1.0 버전이고, 1.0.1에서도 동일합니다. 애드블럭 종료 후에 창 크기를 조절하면 당연한 말이지만 검은색 영역은 나타나지 않고 그 자리에 광고가 표시됩니다.

**Comment by blurfx** [comment]
문제를 재현하지는 못했으나... 의심가는 부분을 수정한 테스트용 바이너리를 https://github.com/blurfx/KakaoTalkAdBlock/releases/tag/1.2.0-alpha 에 올려두었습니다.

현재 설치된 프로그램 대신 해당 릴리즈에 첨부된 바이너리로 테스트 부탁드립니다.

**Comment by hw0603** [comment]
해당 릴리즈 설치하였으나 문제가 해결되지 않았습니다. 시간이 될 때 다른 기기로 테스트 해 보겠습니다

**Comment by dnsdudwk35** [comment]
안녕하세요. 개발자님. 우선 프로그램 개발해주셔서 감사합니다. 얼마전부터 PC카카오에서 검게 창이 변하면서 깨지는 현상이 발생하여, 아무래도 Adblock 문제일 거라 생각했는데 이슈가 있어 공유드립니다.
해당 프로그램 미실행 시 이슈 발생하지 않습니다.
저도 v1.1.0 버전입니다. 2주 정도 사용하였는데 꾸준히 문제가 발생합니다.
현재 Windows10 Education 21H1 19043.1110 이며 모니터3대에 최신버전 사용중입니다.
배율은 100% 사용중입니다.

알파 버전을 사용해보았으나 문제 동일 발생합니다.

주로 문제는 PC 카톡 대화창은 문제없고 채팅창 목록에서 상단의 5mm 정도만을 제외한 나머지가 검게 변합니다.
최소화 후 다시 창을 로딩시키면 문제가 사라집니다.

추가적인 리포트나 자료 필요하시면 공유드리겠습니다.

감사합니다.

**Comment by blurfx** [comment]
@dnsdudwk35 감사합니다. 확인해보겠습니다.

**Comment by dnsdudwk35** [comment]
![kakao_adb_issue](https://user-images.githubusercontent.com/28841591/128614886-bcf4a03c-5fef-4fb7-ad3c-432a18f28315.jpg)

@blurfx 스크린샷 함께 첨부드립니다. 감사합니다 ^^

**Comment by DS-GitHub** [comment]
Windows 10 Pro 21H1 19043.1151 사용중입니다. 아무 문제 없이 정상작동합니다.

**Comment by HwangHanGyeol** [comment]
@dnsdudwk35 이분과 동일한 증상 컴퓨터 총 3대에서 발생하였고, 약 2-3개월 동안 지속되었습니다.
윈도우 Windows 10 Pro 20H2 19042.1165
카카오톡 3.3.2.2905
나머지 2대는 정확한 정보 확인은 불가합니다.
포맷하고 사용해도 동일한 증상입니다.
시간이 지나면 검정색이 풀리며 정상 작동할 때도 있습니다.
정확한 알고리즘은 모르겠지만, 지우고 화면 리프래쉬가 안되서 그런 느낌입니다.
해당 버그 수정되면 좋겠습니다~
감사합니다!

**Comment by blurfx** [comment]
1.2.0 버전에서 수정되었습니다. 같은 문제가 재현되면 이슈 다시 열어주세요.

**Comment by hw0603** [comment]
#48 릴리즈 setup.exe로 설치 진행했는데, 제어판 상에서는 1.2.0으로, 시스템 트레이에서는 1.1.0버전으로 표시되며 해당 증상 여전히 남아 있습니다. 제어판에서 삭제하고 재설치해도 동일 증상이고, 수동삭제하려고 했더니 ```%LocalAppData%\Apps\2.0``` 경로에는 kakao로 시작하는 하위 폴더가 없네요. 설치법이 잘못된 건가요?

**Comment by blurfx** [comment]
@HW

**Comment by blurfx** [comment]
@hw0603 1.2.0에서 해결한 이슈와 다른 문제로 보이는데 문제의 재현 방법을 상세히 설명해주실 수 있으신가요?
(몇 개의 채팅창이 보이고, 최소화 되어있고, 메인 윈도우는 어떤 상태인지[최소화 되어 있다가 다시 복구한 상태인지 등])

**Comment by blurfx** [comment]
@hw0603 예전에 간헐적으로 문제가 나타난다고 해주셨는데 혹시 조정 후 임의의 시간이 지나면 다시 레터박스가 사라지나요? 혹은 영구적으로 남아있나요?

**Comment by hw0603** [comment]
@blurfx
크게 문제가 두 가지가 있었는데,
1. 카카오톡 실행 시 채팅 창 목록과 광고 배너 부분이 모두 레터박스로 나타나는 경우
2. 카카오톡 창 크기 조절 시 광고 배너 부분이 레터박스가 되는 경우

1번 문제는 시간이 지나면 채팅창 목록의 레터박스에 한해서 사라지는 경우가 있었고, 2번 문제는 시간이 지나도 레터박스가 여전히 남아 있었습니다.

> #48 릴리즈 setup.exe로 설치 진행했는데, 제어판 상에서는 1.2.0으로, 시스템 트레이에서는 1.1.0버전으로 표시되며 해당 증상 여전히 남아 있습니다. 제어판에서 삭제하고 재설치해도 동일 증상이고, 수동삭제하려고 했더니 `%LocalAppData%\Apps\2.0` 경로에는 kakao로 시작하는 하위 폴더가 없네요. 설치법이 잘못된 건가요?

여기서 언급한 문제는 1.2.0의 문제가 아니라 1.2.0으로의 업데이트 자체가 안 된 것 같은 느낌을 받았습니다. 제어판에서는 1.2.0.0으로 표시되긴 하지만 실제 실행되는 프로그램의 트레이 아이콘을 우클릭했을 때는 1.1.0으로 여전히 표시되어서 개발자분께서 일부러 메뉴에 1.1.0으로 표시되게 하신 것이 아니라면 무엇인가 오류가 있는 것 같네요..

![화면 캡처 2021-09-11 175208](https://user-images.githubusercontent.com/31981462/132942355-1e8d2632-9d68-4241-9b63-2d8aa8e7257d.png)

![화면 캡처 2021-09-11 175426](https://user-images.githubusercontent.com/31981462/132942369-f6ef5b82-ab52-4224-80ba-f5aabc3cdded.png)

**Comment by blurfx** [comment]
@hw0603 

1.1.0로 표기되는건 제가 실수로 1.2.0으로 바꾸지 않아서 그렇습니다.

말씀해주신 1번 문제는 1.2.0에서 해결을 했는데, 아마 같은 원인으로 인해 나타난 현상이라면 해결되었을 것 같습니다.

2번 문제 같은 경우는 비슷하게 재현은 되나 제가 재현한 방법으로는 일정 시간이 지나면 다시 원래대로 돌아오는 상황인데, 원인은 같은걸로 보입니다. 해당 문제를 해결한 테스트 버전의 링크를 여기에 따로 남겨놓겠습니다.

**Comment by blurfx** [comment]
@hw0603 https://github.com/blurfx/KakaoTalkAdBlock/releases/tag/1.3.0-next.0 테스트 릴리즈 확인해주세요

**Comment by hw0603** [comment]
@blurfx 설치법이 그냥 ```setup.exe``` 만 실행하면 업데이트가 되는게 맞죠? 맞다면 여전히 고쳐지지 않은 것 같네요..

**Comment by blurfx** [comment]
아뇨, 릴리즈 본문에 .zip파일이 있고 압축을 풀면 바로 실행되는 바이너리가 있습니다.

2021년 9월 12일 (일) 오후 5:03, HyungUk Ryu ***@***.***>님이 작성:

**Comment by hw0603** [comment]
@blurfx 기존 설치된 프로그램 종료-> pre-release 바이너리 실행 -> 광고 없어짐 -> 창 크기 조정 후 레터박스 발생

이전과 동일합니다ㅠㅠ

**Comment by blurfx** [comment]
@hw0603 제 환경에서는 원인을 찾기 힘들어서 로그를 한번 요청드리려고 합니다.

이전과 같이 아래 릴리즈에 본문에 포함된 압축파일에 있는 바이너리를 실행시켜주세요.
바이너리가 위치한 곳에 `kakaotalkadblock-logs.txt`가 생깁니다.
로그가 계속 쌓이니 문제를 재현 후 adblock을 종료해주세요.

로그는 iam@xo.dev 로 보내주시면 됩니다.

https://github.com/blurfx/KakaoTalkAdBlock/releases/tag/1.3.0-next.1.log

**Comment by hw0603** [comment]
https://pastebin.com/32ppwfUF

이번 버전에서는 레터박스가 생기기는 하는데 창 크기 조절 중에만 생기고, 마우스 클릭을 해제하면 다시 레터박스가 사라지네요. 그래도 창 여러번 조정해 가면서 생긴 로그 첨부해 드립니다! (현재 네이버 메일에서 첨부파일 등록이 계속 오류나서 pastebin으로 대체했습니다)

**Comment by dnsdudwk35** [comment]
@blurfx 저는 1.2.0 버전 이후 여태까지는 문제 발생하지 않고있습니다. 문제 발생 시 저도 함께 로그 첨부해서 보내도 될까요? 업데이트 하시느라 고생많으십니다. 참고로 저는 윈 11에서 사용 중입니다.

**Comment by blurfx** [comment]
@hw0603 감사합니다.
이번 버전에서는 로그 남기는 부분 외에 작업한 것이 없어 말씀하신대로라면 정상적으로 잘 작동하는 것으로 보입니다.
로그에도 딱히 특별한 부분은 없어서 1.3.0 배포를 해보도록 하겠습니다.

@dnsdudwk35 넵

**Comment by BraINstinct0** [comment]
오늘 업데이트로 받은 1.3.0부터 PC(윈11)에서 카카오톡 채팅에 우클릭 후 첫 메뉴는 보이지만, 거기서 (예를 들어 삭제) 한 단계 더 들어간 메뉴 (모두에게서 삭제 등)가 순간적으로만 보이고 unclickable한 상태가 됩니다. 스크린샷은 아래와 같습니다.
그 업데이트 전까지는 정상작동하였습니다.
![image](https://user-images.githubusercontent.com/29201475/133022820-5314e08e-d700-466b-b8b5-e6d1a162f84f.png)
카카오톡애드블락1.3.0 버전, 카톡은 3.3.3.2911입니다.
설치 제거후 1.2.0을 설치한 뒤 문제가 사라지는지 확인 후업로드해보겠습니다.

**Comment by BraINstinct0** [comment]
![image](https://user-images.githubusercontent.com/29201475/133022968-81b21fc8-904e-4163-905f-4143bc64b93a.png)
1.2.0까지는 없던 현상인데, 1.3.0으로 오늘 업데이트 한 후 발생한 현상입니다.
Win11 22000.186?7? 사용중,
카톡 3.3.3.2911입니다.
첫 우클릭 메뉴는 잘 보이나 한 레벨 더 간 메뉴는 순간적으로 보였다가 사라집니다. 클릭되지 않습니다. 다만 사라지기 전 타이밍 맞게 바로 클릭시 정상 실행됩니다.(보이지 않는 문제는 해결되지 않음)
일단 1.2.0으로 롤백 후 해당 문제가 계속되는지 확인하여 보고드리겠습니다.

**Comment by blurfx** [comment]
@BraINstinct0 해당 문제에 관한 #50 을 만들었습니다.

이 이슈는 동일 증상 발생하기 전까지 닫겠습니다.
