### ISSUE TITLE
로그아웃 후 창이 테두리만 보임

### ISSUE THREAD

**Issue by KENNYSOFT** [blurfx/KakaoTalkAdBlock#42]
### Version Information

KakaoTalkPC: 3.2.9.2815
KakaoTalkAdBlock: 1.0.1

![image](https://user-images.githubusercontent.com/6624567/124342086-2db4d780-dbfc-11eb-8a32-fca8821884c3.png)
▲ KakaoTalkAdblock 켜지 않은 상태로 로그아웃한 상황

![image](https://user-images.githubusercontent.com/6624567/124340519-bded1f80-dbf0-11eb-8ff6-7461434fd5dc.png)
▲ KakaoTalkAdblock 켜고 KakaoTalkPC 창을 끈 다음 트레이에서 클릭하여 다시 켠 상황

**Comment by blurfx** [comment]
fixed in 1.1.0
