### ISSUE TITLE
백신이 Gen:Variant.Bulz.696649 라고 검역하면서 실행이 되지 않습니다

### ISSUE THREAD

**Issue by username0231** [blurfx/KakaoTalkAdBlock#47]
백신은 비트디펜더 사용중이구요..
지금까지 아무 문제 없이 사용중이다가 오늘 갑자기 문제가 발생했습니다.
프로그램이 실행이 안되서 재실행을 해보니 실행하는 족족
백신이 Gen:Variant.Bulz.696649 를 탐지하면서 실행이 되지 않습니다..
설치를 누르면 '응용 프로그램을 검색할 수 없습니다. 인증 오류입니다' 라고 뜹니다.
문제는 백신을 중지해도 여전히 똑같은 오류가 뜹니다.
사용버전은 1.1.0이고, 카톡버전은 Ver. 3.3.3.2911 입니다.

로그 파일 첨부드립니다.

[J1A1ZR4Q.log](https://github.com/blurfx/KakaoTalkAdBlock/files/7136545/J1A1ZR4Q.log)

**Comment by blurfx** [comment]
로그를 확인해보면 백신의 검역소 같은 곳에서 설치에 필요한 파일의 권한을 잡고 있는 것 같습니다.

백신에서 따로 확인해보시면 좋을 것 같습니다.

**Comment by username0231** [comment]
그새 백신이 업데이트 됐는지, 아니면 1.2.0 알파버전을 새로 설치해서 그런건진 모르겠는데
다시 정상작동합니다. 답변 감사합니다.
