### ISSUE TITLE
설치 후 Trojan:Win32/Bearfoos.A!ml 바이러스 검출됨

### ISSUE THREAD

**Issue by skyblue-bear** [blurfx/KakaoTalkAdBlock#5]
설치 후 Trojan:Win32/Bearfoos.A!ml 바이러스 검출되는 문제가 있습니다.

윈도우 디펜더에서 발견되었습니다.
이슈 확인 부탁드립니다.

사용 OS : Win10 Pro 64 (17134 빌드)
카톡 버전 : 3.0.0.2110 (현시점 최신버전)

**Comment by blurfx** [comment]
검사해보았으나 Windows Defender에서 바이러스로 검출되지 않았습니다. 오진으로 보입니다.

검사한 Windows Defender의 바이러스 정의 버전은 1.291.278.0입니다.

현재 v0.0.5 버전의 virus total 검사 결과도 참고용으로 추가합니다.

https://www.virustotal.com/gui/file/1fc7b084222181389dfdbfed228a1ff4c7a510b6c9b9bcc9f937a2fa0dcffb8c/detection
