### ISSUE TITLE
2depth context menu가 사라지는 현상

### ISSUE THREAD

**Issue by blurfx** [blurfx/KakaoTalkAdBlock#50]

**Comment by BraINstinct0** [comment]
해당 버그가 발생한 경우 아래와 같이 보이게 됩니다.
![image](https://user-images.githubusercontent.com/29201475/133023887-b9a7bfc9-5280-43f2-a292-927691e7dea4.png)

**Comment by blurfx** [comment]
@BraINstinct0 항상 생기는 문제인가요? 아니면 특정 조건에서만 발생하나요?

**Comment by blurfx** [comment]
아 문제 확인했습니다. 해결하고 다음 버전에 수정하겠습니다.

**Comment by blurfx** [comment]
문제 해결된 1.3.1 배포되었습니다.
