### ISSUE TITLE
광고화면이 간혈적으로 뜹니다

### ISSUE THREAD

**Issue by BlackLyric** [blurfx/KakaoTalkAdBlock#52]
![bandicam 2021-09-16 09-47-47-245 복사 2](https://user-images.githubusercontent.com/90808697/133532172-702c277c-db22-4f53-b6f8-165566177aaa.png)
가만히 나두면 갑자기 뜰 때도 있고 다른 채팅창을 열면 사진처럼 아래에 광고가 나옵니다
매번 노고에 감사드리며 버그 픽스 부탁드리겠습니다.

**Comment by ybshin5657** [comment]
저는 Windows 시작 시 화면 우측 하단에 표시되는 카카오톡 광고가 간헐적으로 차단이 안 되는 경우가 있고
카카오톡 내 드롭다운 메뉴가 사라져서 클릭이 안 되는 문제가 있습니다.

**Comment by blurfx** [comment]
Fixed in 1.3.2

**Comment by BraINstinct0** [comment]
Confirming that Issue is resolved on windows 11 22000.194 after this patch
