### ISSUE TITLE
윈도우 재시작시 하단 광고가 표시됩니다.

### ISSUE THREAD

**Issue by ubless607** [blurfx/KakaoTalkAdBlock#53]
윈도우 10 사용중이고, 윈도우 재시작시 하단 광고가 표시됩니다. 프로그램가 백그라운드에서 동작중임에도 불구하고 하단 광고가 표시됩니다.

**Comment by blurfx** [comment]
리포트 감사드립니다. #52 와 중복되는 이슈이므로 이 이슈는 닫겠습니다.
