### ISSUE TITLE
카카오 애드블록 1.3.1 버전 업데이트 후 간헐적인 버그가 발생합니다.

### ISSUE THREAD

**Issue by allojys** [blurfx/KakaoTalkAdBlock#54]
1. 사용중인 시스템 
:  인텔 11세대 i5-1135G7, 내장 그래픽 / 윈도우 10 education 21H1 버전, 빌드 19043.1237 
2. 프로그램 버젼: 1.3.1
3. 설명: 카카오톡 창에서 아래의 특정 조건 만족시 다음과 같이 버그 발생
- 카카오톡 채팅창을 열 때
![화면 캡처 2021-09-19 135434](https://user-images.githubusercontent.com/60881049/133916022-33f8f14d-403d-4ad5-ad06-75f7b8b36705.png)
- 카카오톡 창을 최소화 후 창을 띄웠을 때
![화면 캡처 2021-09-19 135533](https://user-images.githubusercontent.com/60881049/133916052-9359dcfa-2077-487f-b7e6-db633130ede9.png)
-카카오톡을 종료 후 다시 실행 하였을 때
 ![화면 캡처 2021-09-19 135531](https://user-images.githubusercontent.com/60881049/133916080-b2cf0a01-58ff-4d37-b73f-d929f2058851.png)
![화면 캡처 2021-09-19 135533](https://user-images.githubusercontent.com/60881049/133916083-9fdff32b-3b1e-497b-8693-569092724c1c.png)
4. 1.3.0 포함, 이전 버젼에서는 해당 버그가 발생하지 않음

**Comment by blurfx** [comment]
리포트 감사드립니다. #52 와 중복되는 이슈이므로 이 이슈는 닫겠습니다.
