### ISSUE TITLE
1.3.1 버전 패치 후 발생하는 이슈

### ISSUE THREAD

**Issue by AngelofLoveS2** [blurfx/KakaoTalkAdBlock#55]
![1](https://user-images.githubusercontent.com/52461858/134441685-3a9b6416-14cf-4987-8872-9c2ba8ecacd2.PNG)

업데이트 후 위와 같은 오류가 발생하면서 애드블록 실행이 되지 않습니다.

앱 제거 후 재설치 하는 과정에서 동일한 오류가 발생해서 현재 설치 불가능 상태입니다.

===============================================

[F5H0YHRY.log](https://github.com/blurfx/KakaoTalkAdBlock/files/7214609/F5H0YHRY.log)

===============================================

**Comment by blurfx** [comment]
배포 프로그램인 ClickOnce의 문제로 보이는데 아쉽게도 제가 해결할 수 있는 방법은 없어보입니다.

다른 분들도 종종 겪는 이슈라 다른 설치/업데이트 관리 툴을 적용할지 한 번 고려해보겠습니다.
