### ISSUE TITLE
파일 첨부 다이얼로그에서 파일명 사라짐

### ISSUE THREAD

**Issue by ybshin5657** [blurfx/KakaoTalkAdBlock#57]
파일 첨부 다이얼로그에서 파일명이 사라지는 버그가 있습니다.

![1](https://user-images.githubusercontent.com/72844671/134915117-7c26acb7-03fc-4265-862e-600e2bc886d5.png)
아래는 정상 화면
![2](https://user-images.githubusercontent.com/72844671/134915335-123fef5b-70fd-4257-9f7f-5eddb69b1094.png)

**Comment by blurfx** [comment]
해당 문제를 재현하는데 실패했습니다. 사용하시는 카카오톡의 버전과 애드블락의 버전을 알려주세요

**Comment by ybshin5657** [comment]
답변 감사합니다.
해당 문제는 카카오톡 + 애드블락 둘 다 윈도우 시작 시 자동 실행이 될 때만 발생하였습니다. (직접 실행 시 발생 안 함)
그래서 트러블슈팅 중 발견한게 제가 직접 실행하면 애드블락이 1.3.2로 실행되고 자동 실행 시에는 1.3.0으로 실행되더군요.
아예 삭제 후 다시 설치하니 개발자 빌드(development build)라고 표시되는데 해당 증상이 사라졌습니다.
업데이트 과정에서 무언가 꼬인 듯 하네요. 감사히 사용하겠습니다.
