### ISSUE TITLE
1.3.2버전으로 올려도 재부팅 후엔 1.3.1버전 실행되는 문제

### ISSUE THREAD

**Issue by ydh0213** [blurfx/KakaoTalkAdBlock#58]
1.3.1 버전 때 트레이에서 종료했다가 재실행하면 1.3.2버전이 실행되는데,
컴퓨터를 재부팅하고 시작 프로그램으로 KakaoTalkAdBlock이 실행될 때는 또 1.3.1 버전이 실행됩니다.
매번 컴퓨터를 켤 때 마다 한 번 KakaoTalkAdBlock을 종료했다가 다시 실행해줘야 하는 번거로움이 있습니다.

**Comment by blurfx** [comment]
1.3.2버전으로 실행되었을때 부팅 시 자동시작 옵션을 껐다가 다시 켜보시면 해결될 것 같습니다.

**Comment by BraINstinct0** [comment]
해당 방법을 시행했으나, 이제는 Development Build로 뜨는 증상이 있습니다.

**Comment by ydh0213** [comment]
저도 Development Build로 뜨네요.
다만 이제는 1.3.1 버전이 아니기 때문에 결과적으로 1.3.1 버전 때의 문제는 없습니다. ㅎㅎ

**Comment by ynetwork** [comment]
트레이 메뉴에 있는 '윈도우 시작 시 자동실행' 대신 시작 메뉴에 있는 프로그램(KakaotalkAdBlock)을 실행/(시작 프로그램으로 사용)하면 정상적으로 출력이 되더군요.
