### ISSUE TITLE
광고제거후 자동으로 꺼지는 옵션이 있으면 좋을거 같습니다

### ISSUE THREAD

**Issue by sysilion** [blurfx/KakaoTalkAdBlock#6]
어차피 한번 적용후에는 종료했다가 다시 켤때까지 광고 안나오는거같은데 꺼도 되지않을까요?

**Comment by blurfx** [comment]
광고 제거 후 프로그램이 종료된 상태에서 창 크기가 변경되면 광고 영역이 다시 생기는 현상이 있어(물론 광고는 나오지 않습니다) 현재 계속 상주하면서 해당 부분을 제거해주고 있는데요, 상관 없으시다면 끄고 사용하셔도 됩니다. :)

**Comment by sysilion** [comment]
아... 창크기 변경시 다시 공간이 생기는군요... 몰랐네요... ㄷㄷ
