### ISSUE TITLE
설치 과정 중 다운로드 오류

### ISSUE THREAD

**Issue by park-csu** [blurfx/KakaoTalkAdBlock#61]
#### 버그/오류에 대해 설명해주세요
설치 과정에서 '처음 게시된 이후 ~~파일이 변경되었습니다, ~~' 오류가 발생하며 설치가 되지 않습니다

#### 문제를 재현하는 방법을 설명해주세요
가장 최근 setup.exe 실행

#### 스크린샷
![image](https://user-images.githubusercontent.com/55010215/141491995-eb44dc0a-906d-4329-adbf-b254d2a9f726.png)

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: 3.3.4.2956
- 카카오톡 애드블럭: 가장 최근 릴리즈

**Comment by BraINstinct0** [comment]
사용중인 백신에 의해 자동 삭제되었을 수 있습니다.

**Comment by blurfx** [comment]
GitHub의 파일 서빙 불안정 또는 ClickOnce의 오류라 별도 작업 없이 이슈 닫습니다.
