### ISSUE TITLE
카카오톡 실행시 하단 팝업 광고 차단이 안됩니다.

### ISSUE THREAD

**Issue by thekks1452** [blurfx/KakaoTalkAdBlock#62]
#### 버그/오류에 대해 설명해주세요
카카오톡 애드블럭 실행 후 카카오톡을 실행하면 다른 광고는 다 차단이 되지만 실행 시 뜨는 하단 팝업 광고는 차단이 되지 않습니다.

#### 문제를 재현하는 방법을 설명해주세요
카카오톡 애드블럭을 수동 실행 후 카카오톡을 실행하고 약 1~2초 뒤에 하단 팝업 광고가 표시됩니다.

#### 스크린샷
![zkxhrckeksdksehla](https://user-images.githubusercontent.com/79415641/148467963-a428f92b-6234-4f94-b517-989da78dfe7d.jpg)

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: Ver. 3.3.6.2992
- 카카오톡 애드블럭: 1.3.2

**Comment by pimozone** [comment]
저도 이 문제 발생합니다

**Comment by blurfx** [comment]
fixed in [2.1.4](https://github.com/blurfx/KakaoTalkAdBlock/releases)
