### ISSUE TITLE
설치 오류 메시지

### ISSUE THREAD

**Issue by mople0308** [blurfx/KakaoTalkAdBlock#63]
#### 버그/오류에 대해 설명해주세요
아래 이미지와 같은 경고 메시지가 나타나며 설치가 되지 않습니다. 다시시도해도 마찬가지입니다

#### 문제를 재현하는 방법을 설명해주세요
일반 설치, 관리자 권한으로 설치

#### 스크린샷
![image](https://user-images.githubusercontent.com/63803824/153715215-463f10c6-cb62-4349-bbdd-d5f69aae73fa.png)

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: 3.3.7.3022
- 카카오톡 애드블럭: 1.3.2

**Comment by blurfx** [comment]
#61 해결 불가능한 중복 이슈로 닫습니다.
