### ISSUE TITLE
영문 Windows 11에서 설치가 불가능합니다.

### ISSUE THREAD

**Issue by hankju84** [blurfx/KakaoTalkAdBlock#64]
#### 버그/오류에 대해 설명해주세요
영문 Windows 11에서 설치를 시도할 경우 .NET Framework 4.6.2의 설치를 요구하는데, 설치를 시도하면 <%LOCALAPPDATA%\Temp\VSD9F10.tmp\DotNetFX462\NDP462-KB3151800-x86-x64-AllOS-KOR.exe' 파일이 변경되었습니다. [확인]을 클릭하여 다운로드를 다시 시도하거나 [취소]를 클릭하여 설치를 끝내십시오.>와 같은 메시지가 뜨면서 진행되지 않습니다.

#### 문제를 재현하는 방법을 설명해주세요
Windows 11의 표시 언어를 영어로, 비유니코드 프로그램이 사용할 로캘을 한국어로 설정한 상태에서 설치 프로그램을 실행.

#### 스크린샷
![image](https://user-images.githubusercontent.com/73779442/155880810-66f40033-1ab1-4f2d-b070-d86073d287be.png)

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: 3.3.8.3058
- 카카오톡 애드블럭: 1.3.2

**Comment by hankju84** [comment]
작업 불가능 이슈임을 확인.

**Comment by loopback-kr** [comment]
> 작업 불가능 이슈임을 확인.

로캐일이 다른 경우 소스를 클론 받아 (필요 시 .Net 업그레이드 후) Publish 하면 해결 됨.
