### ISSUE TITLE
설치 진행 못해요

### ISSUE THREAD

**Issue by JinstonC** [blurfx/KakaoTalkAdBlock#67]
#### 버그/오류에 대해 설명해주세요
설치 못해요.

#### 문제를 재현하는 방법을 설명해주세요
I get an error:

(10/10/2022 11:37:47 AM) Downloading 'DotNetFX462\NDP462-KB3151800-x86-x64-AllOS-KOR.exe' from 'http://go.microsoft.com/fwlink/?LinkId=780603&clcid=0x412' to 'C:\Users\jinst\AppData\Local\Temp\VSDA3FB.tmp\'
Download completed at 10/10/2022 11:37:47 AM
Verifying file integrity of C:\Users\jinst\AppData\Local\Temp\VSDA3FB.tmp\DotNetFX462\NDP462-KB3151800-x86-x64-AllOS-KOR.exe
WinVerifyTrust returned 0
File trusted
Error: 처음 게시된 이후 'C:\Users\jinst\AppData\Local\Temp\VSDA3FB.tmp\DotNetFX462\NDP462-KB3151800-x86-x64-AllOS-KOR.exe' 파일이 변경되었습니다.

I downloaded and tried to install manually, but I cannot because the installer says .Net is already installed

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: 
- 카카오톡 애드블럭: 1.3.2

**Comment by JinstonC** [comment]
I think the issue is the installer is looking for .NET 4.6.2, but newer Windows 10 installations come with 4.8 and cannot downgrade to 4.6.2. Can you fix the compatibility?

**Comment by watermelonboi22** [comment]
Is there any update on this issue? I'm unable to use adblock anymore due to this.

**Comment by JinstonC** [comment]
Author linked a registry hack on the readme, but it doesn't fix the issue. .NET 4.6.2 is not installable on newer Windows 10 installations.

**Comment by HexagonWin** [comment]
I'm attempting installation on WINE 8.6 on Slackware 15.0 and get the same error.

**Comment by blurfx** [comment]
I'm removing the .NET FX dependency and rewriting it as a native application. native app has a 2.0 major version and just published its first alpha release.

NOTE: Ad removal works, but no features like run at windows startup, tray icons or auto-update exist. and the auto-update feature may not be available in the future.

If you want to run at windows startup, or terminate it after it runs, register a startup program manually and kill process through the task manager.

https://github.com/blurfx/KakaoTalkAdBlock/releases/tag/2.0.0-alpha1

**Comment by watermelonboi22** [comment]
After some trial I was actually able to install it without a problem - forgot the exact steps but I think I was trying to run a different file instead of the one that I had to. Nevertheless, the new update will be useful for those who aren't able to figure out how to install the program. For me, I'll rather keep the previous version as it has more features.
