### ISSUE TITLE
카카오톡 팝업 광고 차단 오류

### ISSUE THREAD

**Issue by SeokHyeonLee** [blurfx/KakaoTalkAdBlock#69]
#### 버그/오류에 대해 설명해주세요
카카오톡 팝업 광고 차단이 안됨

#### 문제를 재현하는 방법을 설명해주세요
보통 컴퓨터 부팅 시 첫 광고가 나오고 다음부턴 나오진 않습니다

#### 스크린샷
![image](https://user-images.githubusercontent.com/54782755/198908704-57e10341-aae4-4c57-9329-ae019b5d23c3.png)

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: 3.4.3.3222
- 카카오톡 애드블럭: release v0.0.12

**Comment by blurfx** [comment]
카카오톡 애드블럭을 최신 버전으로 업데이트 하신 후 같은 현상이 또 일어난다면 이슈 다시 열어주세요.
