### ISSUE TITLE
중복 실행 됩니다

### ISSUE THREAD

**Issue by sleepylion99** [blurfx/KakaoTalkAdBlock#7]
제가 실수로 더블클릭을 두번 클릭 했나봅니다
그런데? 똑같은 아이콘 두개 이더군요
뭐지..? 잘못본건가 하고 끄고
다시 실행하니까 중복 실행 되더군요
중복 실행 방지 추가 해줬으면 좋겠습니다.

**Comment by blurfx** [comment]
v0.0.6에서 수정되었습니다.
