### ISSUE TITLE
시작프로그램 수동등록

### ISSUE THREAD

**Issue by Kirarichirari** [blurfx/KakaoTalkAdBlock#72]
#### 버그/오류에 대해 설명해주세요

이번 업데이트 때문인지 모르겠지만 새로운 버전 받고
안내대로 시작프로그램 수동등록 방법이 2가지 있는데요
shell:startup 를 통해서 바로가기로 넣고 시작시 자동으로 실행
또는 작업스케줄러 만들어서 자동으로 실행

결과는 
재부팅 해도 자동실행되지만 카카오톡 실행하면 광고차단 정상적으로 작동 안됨
혹시나 싶어서 직접 실행하기 누르면 중복 실행되면서 광고차단이 됩니다.

해결 방법이 없을까요?

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: 3.5.5.3553
- 카카오톡 애드블럭: 2.0.0

**Comment by blurfx** [comment]
아마도 [2.1.1](https://github.com/blurfx/KakaoTalkAdBlock/releases)에서 해결되었을겁니다. 문제가 해결되지 않았다면 이슈 다시 열어주세요.
