### ISSUE TITLE
카카오톡 애드블록 실행중에 카카오톡이 종료되면 다시 실행시 광고차단이 적용되지 않습니다.

### ISSUE THREAD

**Issue by allojys** [blurfx/KakaoTalkAdBlock#76]
#### 버그/오류에 대해 설명해주세요
카카오톡 애드블록이 실행 중 카카오톡 프로세스가 종료되면 이후 카카오톡을 다시 열었을 시에 감지를 못하고, 광고차단이 작동하지 않음. 카카오톡 애드블록 프로세스를 재실행해야 다시 광고차단이 작동함

#### 문제를 재현하는 방법을 설명해주세요
카카오톡과 카카오톡 애드블록을 둘다 실행한 상태에서 카카오톡 프로세스만을 종료하고 재실행합니다. 이 때 다시 실행된 카카오톡에서는 광고차단이 작동하지 않는 것을 볼 수 있습니다. 

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: ver. 3.8.0.3829

- 카카오톡 애드블럭: 2.0.0

**Comment by blurfx** [comment]
fixed in [2.1.1](https://github.com/blurfx/KakaoTalkAdBlock/releases)
