### ISSUE TITLE
카카오톡 메인창이 채팅창보다 상단으로 고정되는 버그가 있습니다

### ISSUE THREAD

**Issue by username0231** [blurfx/KakaoTalkAdBlock#80]
#### 버그/오류에 대해 설명해주세요

카카오톡 메인창이 다른 채팅창보다 항상 최상단으로 고정됩니다.
다른 프로그램의 위로 올라오지는 않고, 카카오톡 채팅창만 가려집니다

#### 스크린샷

![16574321](https://github.com/blurfx/KakaoTalkAdBlock/assets/90395203/af7fe40b-3af3-44c3-8624-48ec2b9bacb7)

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: 4.0.0.3873
- 카카오톡 애드블럭: 구 버전을 사용하다가 최근 카톡 4.0 업뎃 이후 구버전을 삭제하고, 2.1.1 버전을 다운받아 설치했습니다

**Comment by blurfx** [comment]
fixed in [2.1.2](https://github.com/blurfx/KakaoTalkAdBlock/releases)
