### ISSUE TITLE
작업표시줄에서 종료 불가능

### ISSUE THREAD

**Issue by Shane1230** [blurfx/KakaoTalkAdBlock#81]
#### 버그/오류에 대해 설명해주세요

~~작업표시줄에서 종료가 안됩니다. 더블클릭, 우클릭 모두 사용 불가능.~~
재부팅으로 해결되었습니다.

또한 프로그램을 한번 더 켜면 프로그램이 2개 켜집니다.
amd64, i386모두 동일

#### 문제를 재현하는 방법을 설명해주세요

윈도우 11 23H2 사용중입니다.

#### 스크린샷

![image](https://github.com/blurfx/KakaoTalkAdBlock/assets/32366080/4b8e05c8-3fa8-4cab-8728-5420f29fabd9)

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: 4.0.0.3873
- 카카오톡 애드블럭: 2.1.2

**Comment by ee5ee** [comment]
윈도우 실행 시 자동 실행도 안 되는 게 맞죠?

**Comment by Shane1230** [comment]
> 윈도우 실행 시 자동 실행도 안 되는 게 맞죠?

shell:startup에 넣으니 잘 작동하네요. i386 사용했습니다.

**Comment by allojys** [comment]
컴퓨터 재부팅 해보셨나요?

**Comment by Shane1230** [comment]
> 컴퓨터 재부팅 해보셨나요?

어? 뭐야 해결되었어요 감사합니다.

**Comment by allojys** [comment]
> > 컴퓨터 재부팅 해보셨나요?
> 
> 어? 뭐야 해결되었어요 감사합니다.

issue close 하시죠
