### ISSUE TITLE
메인창 하단 광고 차단 불가

### ISSUE THREAD

**Issue by dateno1** [blurfx/KakaoTalkAdBlock#82]
#### 버그/오류에 대해 설명해주세요

https://github.com/blurfx/KakaoTalkAdBlock/issues/77 이 고쳐진걸로 되어있지만 여전히 동일한 상태

3.8대의 카톡을 사용할떄는 케케묵은 1.1대도 정상적으로 차단되었습니다

#### 문제를 재현하는 방법을 설명해주세요

4대 버전 실행

#### 스크린샷

![image](https://github.com/blurfx/KakaoTalkAdBlock/assets/12645246/f2806650-bdf0-4724-b266-edca9265111d)

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: 4.0.0.3873
- 카카오톡 애드블럭: 2.1.2

이외에 구버전은 트레이 아이콘에 우클릭시 종료등의 메뉴가 나왔지만, 최신 버전은 좌우 클릭 다 아무 반응이 없습니다

**Comment by blurfx** [comment]
해당 현상은 재현 불가입니다. 최신 버전을 실행했는지 다시 확인해주세요.

2.x 버전부터는 트레이 아이콘 우클릭시 메뉴가 나오지 않습니다. 아이콘 더블 클릭으로 종료하시면 됩니다.

**Comment by dateno1** [comment]
> 해당 현상은 재현 불가입니다. 최신 버전을 실행했는지 다시 확인해주세요.
> 
> 2.x 버전부터는 트레이 아이콘 우클릭시 메뉴가 나오지 않습니다. 아이콘 더블 클릭으로 종료하시면 됩니다.

https://www.mediafire.com/?zys2p70wtuk8cju
시험에 사용된 portable 버전입니다

압축 해제후 단일 exe로 되어있는 파일을 실행하면 됩니다

https://www.mediafire.com/?926m1xiojuf74tv
3.8 portable 버전은 구버전인 1.1.0 (21년에 받은 파일로 문제 없어서 계속 사용함)로 시험시 정상적으로 제거되었습니다

3.8 portable으로 정상 제거 확인 -> exe만 교체해서 4대로 업글 -> 1.1.0으로 제거 안 되는것 확인 -> adblock만 2.1.2(x86)로 업글
이렇게 진행되었습니다

참고로 portable이라고 딱히 메모리 영역 접근 불가나 주소 크게 바뀌는것 없습니다 (https://github.com/loopback-kr/KakaoTalkADGuard 1.0.0.4경우 정상 제거됨)

**Comment by blurfx** [comment]
포터블 환경에서 같은 이름의 VM 프로세스를 실행하여 발생한 문제입니다. [2.1.3](https://github.com/blurfx/KakaoTalkAdBlock/releases)에서 해결되었습니다.
