### ISSUE TITLE
v.2.1.3 KakaoTalkAdBlock_amd64.exe 보안 관련

### ISSUE THREAD

**Issue by ydh0213** [blurfx/KakaoTalkAdBlock#83]
#### 버그/오류에 대해 설명해주세요

v.2.1.3 KakaoTalkAdBlock_amd64.exe 다운로드를 하려고 하면 바이러스가 포함되어 있다는 보안 경고가 Chrome에서 뜨며, 다운 받더라도 Windows11 기준 Defender가 강제로 조치를 취하고 있습니다.

#### 스크린샷

![image](https://github.com/blurfx/KakaoTalkAdBlock/assets/8025481/3353414d-3dd7-42de-9882-479ce9f48b8c)

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: v.4.0.0
- 카카오톡 애드블럭: v.2.1.3

**Comment by blurfx** [comment]
다른 프로세스(카카오톡)의 윈도우에 접근하는 방식이라 발생하는 문제입니다. 디펜더에서 격리 해제 하고 쓰시면 됩니다.
