### ISSUE TITLE
Window Defender 오진 (2.1.1 이후)

### ISSUE THREAD

**Issue by SeokHyeonLee** [blurfx/KakaoTalkAdBlock#85]
#### 버그/오류에 대해 설명해주세요
2.1.1 이후 버전 다운로드 시 Window Defender에서 Trojan:Win32/Acll 로 오진합니다.

#### 문제를 재현하는 방법을 설명해주세요
Window Defender가 활성화 된 상태에서 웹 브라우저에서 KakaoTalkAdBlock_amd64.exe 다운로드 시도

#### 스크린샷
![image](https://github.com/blurfx/KakaoTalkAdBlock/assets/54782755/935a2c67-f17b-4397-bbdd-6b27c00310bc)

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: x
- 카카오톡 애드블럭: 2.1.1 버전 이후

**Comment by SeokHyeonLee** [comment]
> possible duplicate of #83

https://www.microsoft.com/en-us/wdsi
submit files
마이크로소프트에 개발자가 직접 오진 신청을 넣고 프로그램 검사를 진행할 수 있습니다.

**Comment by luftaquila** [comment]
저도 제가 배포한 바이너리가 탐지에 걸려서 신청해본 적이 있는데요, 버전 업데이트로 바이너리가 바뀌면 매번 다시 재신청해야 하더라고요. 오탐 해제되는데까지는 몇 달 정도 걸렸던 것 같습니다.

**Comment by blurfx** [comment]
2.1.4 버전 바이너리가 멀웨어 감지 목록에서 제외되었다는 답변을 받았습니다. 이전 버전은 따로 처리하지 않겠습니다.
