### ISSUE TITLE
ver. 4.0.0.3881 기준 업데이트 후 설정 아이콘이 움직입니다

### ISSUE THREAD

**Issue by Dvarw** [blurfx/KakaoTalkAdBlock#86]
#### 버그/오류에 대해 설명해주세요

업데이트 후 설정 아이콘이 움직입니다

#### 스크린샷

![ka](https://github.com/blurfx/KakaoTalkAdBlock/assets/168043810/a278d421-39cd-4b66-b4c6-d25b78f5e804)

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: ver. 4.0.0.3881 
- 카카오톡 애드블럭: 2.1.4

**Comment by blurfx** [comment]
저는 업데이트 후 해당 문제가 발생하지 않습니다. 이슈 재현 방법을 알려주세요.

**Comment by Dvarw** [comment]
평소처럼 컴퓨터 부팅-카카오톡 윈도우 시작시 자동으로 시작-애드블럭 shell::startup 폴더에 setup파일 바로가기 넣고 실행시키는 중인데 회사와 집에서 동일하게 설정 아이콘이 움직이는 현상이 발생했습니다

두군데서 동일한 현상이 발생해서 프로그램에 이슈가 있을까 싶어 올렸는데 재설치하고 다시 동일한 방법으로 테스트해보겠습니다

**Comment by Dvarw** [comment]
방금 확인하였고, 기존의 setup파일 바로가기와 새로 업데이트 된 setup파일이 두개가 동시에 실행되어 생기는 이슈로 확인되었습니다
