### ISSUE TITLE
VirusTotal 오진 및 Scoop 등록 관련

### ISSUE THREAD

**Issue by oxjihun** [blurfx/KakaoTalkAdBlock#88]
#### 버그/오류에 대해 설명해주세요

VirusTotal이 2.1.4 버전의 바이너리를 멀웨어로 인식합니다. 

우선 윈도우 디펜더의 오진은 해결되었기 때문에 앱 사용에는 문제가 없습니다. VirusTotal의 오진이 문제가 되었던 것은 제가 Scoop이라는 프로젝트에 기여를 시도했기 때문입니다. Scoop이 어떤 프로젝트인지에 관해서는 공식 홈페이지인 <https://scoop.sh/>를, 문제가 된 PR에 관해서는 <https://github.com/ScoopInstaller/Extras/pull/12968>을 참고해주시면 좋겠습니다. 간단히 요약하자면 Scoop으로 설치 가능한 앱 목록에 카카오톡 애드블럭을 추가하려 했는데 바이너리의 VirusTotal 검진 결과가 문제시된 것입니다. 

VirusTotal의 오진에 대한 수정 요청을 개발자 측에서 넣을 수 있는지 여쭙는 목적도 있지만, 다른 프로젝트에서 이런 불미스러운 일이 발생한 것을 알리는 것이 무엇보다 중요하다 생각하여 이 이슈를 작성하게 되었습니다. 

#### 스크린샷

![amd64](https://github.com/blurfx/KakaoTalkAdBlock/assets/91365109/b776b7af-dc10-48db-a892-a851cd174df8)
![i386](https://github.com/blurfx/KakaoTalkAdBlock/assets/91365109/2e637625-14a0-4df3-a055-1d936442f189)

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: -
- 카카오톡 애드블럭: 2.1.4

**Comment by blurfx** [comment]
False Positive 결과를 내는 백신 벤더들에게 연락을 해보겠습니다. 마침 VirusTotal이 정리해둔게 있네요. https://docs.virustotal.com/docs/false-positive-contacts

다만 프로그램 동작 방식의 특성상 False Positive를 벗어나지 못할수도 있을 것 같습니다.

**Comment by blurfx** [comment]
일부 벤더들에게 false positive 처리가 되었고 virus total에 나중에 반영될 것이라는 답변을 받았습니다.

다른 문제가 없다면 이 이슈는 나중에 닫겠습니다.

**Comment by ix-hammer-turtle** [comment]
sentinel one 에서도 virus라고 오탐하네요

**Comment by blurfx** [comment]
백신 벤더들에게서 더 이상 응답이 없으므로 닫습니다.
