### ISSUE TITLE
build.bat 실행 후 카카오톡 로그인 불가 현상

### ISSUE THREAD

**Issue by bakaseon** [blurfx/KakaoTalkAdBlock#91]
#### 버그/오류에 대해 설명해주세요

안녕하세요. 멍청하게도 build.bat을 실행한 후 [카카오톡 로그인 서버에 연결할 수 없습니다. 사용자 네트워크 연결이 불안정 하거나, 방화벽 등에 의해 카카오톡 사용이 차단된 환경일 수 있습니다. 
이 오류가 반복 되면 네트워크 관리자에게 문의 하세요. (오류코드 : AN, 10060, LO]
라는 문구가 뜨면서 로그인이 되지 않습니다.

#### 문제를 재현하는 방법을 설명해주세요

build.bat 파일을 실행하고 난 후 이렇게 되었습니다.

#### 카카오톡, 카카오톡 애드블럭 버전을 알려주세요
- 카카오톡: 
- 카카오톡 애드블럭:

**Comment by blurfx** [comment]
지금 카카오톡 서버에 로그인 이슈가 있어서 발생하는 현상입니다. 말씀하신 것과는 무관한 이슈입니다.
